server:
  port: 8080
spring:
  redis:
    url: "redis://127.0.0.1:6379"
  application:
    name: dubbo-provider-demo
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test
    username: root
    password: admin
dubbo:
  application:
    name: dubbo-provider-demo
  protocol:
    name: dubbo
    port: -1
  registry:
    id: zk-registry
    address: zookeeper://127.0.0.1:2181
  config-center:
    address: zookeeper://127.0.0.1:2181
  metadata-report:
    address: zookeeper://127.0.0.1:2181
  provider:
    threads: 2000
    timeout: 60000
    retries: 1
  consumer:
    retries: 1
    timeout: 60000
mybatis:
  configuration:
    map-underscore-to-camel-case: true